framework:
  messenger:
    #-------------------------------------------------------------------------------------------------------------------
    #
    # IMPORTANT NOTES ABOUT MESSENGER:
    #
    # 1) The following must be executed
    #        php bin/console messenger:consume async_communication -vv --limit=10 --memory-limit=128M
    #
    # 2) This command should be managed by supervisord.
    #
    # 3) One of the following variables should be set on the .env file
    #     a) MESSENGER_TRANSPORT_DSN=doctrine://default
    #     b) MESSENGER_TRANSPORT_DSN=amqp://guest:guest@localhost:5672/%2f/messages
    #     c) MESSENGER_TRANSPORT_DSN=redis://localhost:6379/messages
    #
    #-------------------------------------------------------------------------------------------------------------------

    reset_on_message: true

    # After a message failed in every retry, it's added to this transport.
#    failure_transport: failed

    transports:
      # doctrine transport.
      async_communication: "%env(MESSENGER_TRANSPORT_DSN)%"

      sync: 'sync://'

    routing:
      # Email Notification message will be handled by `async_communication` transport.
      'App\EmailNotifier\EmailNotification': async_communication


