parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Twig\Extensions\TextExtension: ~
    Common\View\Twig\Filter\DashedPhoneTwigExtension: ~

    logger:
       alias: 'monolog.logger'
       public: true

    App\Demo\Generator\EntityGenerator:
        class: App\Demo\EntityGenerator
        public: true,
        arguments: [ '@doctrine.orm.entity_manager']
        tags:
          [ 'doctrine.fixture.orm' ]

    App\Demo\Generator\EntityGeneratorCommand:
        class: App\Demo\EntityGeneratorCommand
        public: true,
        arguments: [ '@App\Demo\Generator\EntityGenerator']

    App\Entity\Business\GoogleReviewManager\GoogleReviewManager:
        class: App\Entity\Business\GoogleReviewManager\GoogleReviewManager
        public: true

    App\Google\GoogleMap\Place\Services:
        class:
        arguments:
            - '%google_map_api_key%'

    Common\Communication\Mailer\SendGrid\Mailer:
        class: Common\Communication\Mailer\SendGrid\Mailer
        arguments:
            - '%sendgrid_api_key%'
            - '%sender_email%'
            - '%sender_name%'

    Common\Communication\HtmlMailer\Mailer:
        class: Common\Communication\HtmlMailer\Mailer
        public: true
        arguments:
            - '@mailer'
            - '@logger'
            - '%sender_email%'
            - '%internal_to_email%'
            - '%sender_name%'

    App\Google\GoogleMap\Place\Core\Transport\Transport:
        class: App\Google\GoogleMap\Place\Core\Transport\Transport
        public: yes
        arguments:
            - '%google_map_api_key%'

    App\Google\GoogleMap\Place\Services\PlaceAutocomplete\PlaceAutocompleteService:
        class: App\Google\GoogleMap\Place\Services\PlaceAutocomplete\PlaceAutocompleteService
        public: yes
        arguments:
            - '@App\Google\GoogleMap\Place\Core\Transport\Transport'
            - '%google_map_api_key%'

    App\Google\GoogleMap\Place\Services\PlaceDetails\PlaceDetailsService:
        class: App\Google\GoogleMap\Place\Services\PlaceDetails\PlaceDetailsService
        public: yes
        arguments:
            - '@App\Google\GoogleMap\Place\Core\Transport\Transport'
            - '%google_map_api_key%'

    App\Api\Core\Services\GoogleReviewManager\ApiGoogleReviewManager:
        class: App\Api\Core\Services\GoogleReviewManager\ApiGoogleReviewManager
        public: yes
        arguments:
            - '%google_write_review_base_url%'
