parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    logger:
       alias: 'monolog.logger'
       public: true

    App\Demo\Generator\EntityGenerator:
        class: App\Demo\EntityGenerator
        public: true,
        arguments: [ '@doctrine.orm.entity_manager']
        tags:
          [ 'doctrine.fixture.orm' ]

    App\Demo\Generator\EntityGeneratorCommand:
        class: App\Demo\EntityGeneratorCommand
        public: true,
        arguments: [ '@App\Demo\Generator\EntityGenerator']

    App\Entity\Business\GoogleReviewManager\GoogleReviewManager:
        class: App\Entity\Business\GoogleReviewManager\GoogleReviewManager
        public: true

    Common\Communication\Mailer\SendGrid\Mailer:
        class: Common\Communication\Mailer\SendGrid\Mailer
        arguments:
            - '%sendgrid_api_key%'
            - '%sender_email%'
            - '%sender_name%'

    Common\Communication\HtmlMailer\Mailer:
        class: Common\Communication\HtmlMailer\Mailer
        public: true
        arguments:
            - '@mailer'
            - '@logger'
            - '%sender_email%'
            - '%internal_to_email%'
            - '%sender_name%'